use VIVADIVINA

DROP TABLE CAIXAS

CREATE TABLE REGIAO 
(CD_REGIAO INT IDENTITY (1,1) NOT NULL,
NM_REGIAO VARCHAR(12) NOT NULL,
CONSTRAINT PK_REGIAO PRIMARY KEY (CD_REGIAO))


INSERT INTO REGIAO VALUES ('SUL')
INSERT INTO REGIAO VALUES ('SUDESTE')
INSERT INTO REGIAO VALUES ('CENTRO-OESTE')
INSERT INTO REGIAO VALUES ('NORTE')
INSERT INTO REGIAO VALUES ('NORDESTE')

SELECT * FROM REGIAO

CREATE TABLE ESTADO
(CD_ESTADO INT IDENTITY (1,1) NOT NULL,
NM_ESTADO VARCHAR(50) NOT NULL,
DS_SIGLA VARCHAR(2) NOT NULL,
CD_REGIAO INT NOT NULL,
CONSTRAINT PK_ESTADO PRIMARY KEY (CD_ESTADO),
CONSTRAINT FK_REGIAO FOREIGN KEY (CD_REGIAO) REFERENCES REGIAO (CD_REGIAO))

DROP TABLE ESTADO VALUES 


--INICIADO A PARTIR DO ITEM 33 DO DIA 7/3/2024--
INSERT INTO ESTADO VALUES ('RIO GRANDE DO SUL','RS',1)
INSERT INTO ESTADO VALUES ('SANTA CATARINA','SC',1)
INSERT INTO ESTADO VALUES ('PARANÁ','PR',1)
INSERT INTO ESTADO VALUES ('SÃO PAULO','SP',2)
INSERT INTO ESTADO VALUES ('RIO DE JANEIRO','RJ',2)
INSERT INTO ESTADO VALUES ('MINAS GERAIS','MG',2)
INSERT INTO ESTADO VALUES ('ESPÍRITO SANTO','ES',2)
INSERT INTO ESTADO VALUES ('MATO GROSSO DO SUL','MS',3)
INSERT INTO ESTADO VALUES ('MATO GROSSO','MT',3)
INSERT INTO ESTADO VALUES ('GOIÁS','GO',3)
INSERT INTO ESTADO VALUES ('BRASÍLIA','DF',3)
INSERT INTO ESTADO VALUES ('TOCANTINS','TO',4)
INSERT INTO ESTADO VALUES ('ACRE','AC',4)
INSERT INTO ESTADO VALUES ('AMAZONAS','AM',4)
INSERT INTO ESTADO VALUES ('RONDÔNIA','RO',4)
INSERT INTO ESTADO VALUES ('RORAIMA','RR',4)
INSERT INTO ESTADO VALUES ('AMAPÁ','AP',4)
INSERT INTO ESTADO VALUES ('PARÁ','PA',4)
INSERT INTO ESTADO VALUES ('MARANHÃO','MA',5)
INSERT INTO ESTADO VALUES ('PIAUÍ','PI',5)
INSERT INTO ESTADO VALUES ('CEARÁ','CE',5)
INSERT INTO ESTADO VALUES ('RIO GRANDE DO NORTE','RN',5)
INSERT INTO ESTADO VALUES ('PARAÍBA','PB',5)
INSERT INTO ESTADO VALUES ('PERNAMBUCO','PE',5)
INSERT INTO ESTADO VALUES ('ALAGOAS','AL',5)
INSERT INTO ESTADO VALUES ('SERGIPE','SE',5)
INSERT INTO ESTADO VALUES ('BAHIA','BA',5)

SELECT NM_REGIAO 'REGIAO', CD_ESTADO 'CÓD ESTADO', NM_ESTADO 'ESTADO', DS_SIGLA 'SIGLA' FROM REGIAO AS R
INNER JOIN ESTADO AS E ON E.CD_REGIAO=R.CD_REGIAO 


CREATE TABLE CIDADE 
(CD_CIDADE INT IDENTITY (1,1) NOT NULL,
NM_CIDADE VARCHAR(50) NOT NULL,
CD_ESTADO INT NOT NULL,
CONSTRAINT PK_CIDADE PRIMARY KEY (CD_CIDADE),
CONSTRAINT FK_ESTADO FOREIGN KEY (CD_ESTADO) REFERENCES ESTADO (CD_ESTADO)) 

--INICIADO A PARTIR DO ITEM 33 DO DIA 7/3/2024--
INSERT INTO CIDADE VALUES ('JOINVILLE',2)
INSERT INTO CIDADE VALUES ('RIO DE JANEIRO',5)
INSERT INTO CIDADE VALUES ('PORTO ALEGRE',1)
INSERT INTO CIDADE VALUES ('SOROCABA',4)
INSERT INTO CIDADE VALUES ('FORTALEZA',21)
INSERT INTO CIDADE VALUES ('ITAPEMA',2)
INSERT INTO CIDADE VALUES ('SÃO PAULO',4)
INSERT INTO CIDADE VALUES ('SÃO JOSÉ DOS CAMPOS',4)
INSERT INTO CIDADE VALUES ('GUANAMBI',27)
INSERT INTO CIDADE VALUES ('CAJAMAR',4)
INSERT INTO CIDADE VALUES ('PRAIA GRANDE',4)
INSERT INTO CIDADE VALUES ('TUPÃ',4)
INSERT INTO CIDADE VALUES ('FRANCO DA ROCHA',4)
INSERT INTO CIDADE VALUES ('BRASÍLIA',11)
INSERT INTO CIDADE VALUES ('COTIA',4)
INSERT INTO CIDADE VALUES ('CAXIAS DO SUL',1)
INSERT INTO CIDADE VALUES ('SANTO ANDRÉ',4)
INSERT INTO CIDADE VALUES ('OSASCO',4)
INSERT INTO CIDADE VALUES ('TERESÓPOLIS',5)
INSERT INTO CIDADE VALUES ('SÃO JOÃO DA BOA VISTA',4)
INSERT INTO CIDADE VALUES ('JACAREÍ',4)
INSERT INTO CIDADE VALUES ('TAQUARA',1)

SELECT NM_REGIAO 'REGIAO', NM_ESTADO 'ESTADO', DS_SIGLA 'SIGLA', NM_CIDADE 'CIDADE', CD_CIDADE 'CÓD CIDADE' FROM REGIAO AS R
INNER JOIN ESTADO AS E ON R.CD_REGIAO=E.CD_REGIAO
INNER JOIN CIDADE AS C ON C.CD_ESTADO=E.CD_ESTADO 


CREATE TABLE BAIRRO
(CD_BAIRRO INT IDENTITY (1,1) NOT NULL,
NM_BAIRRO VARCHAR(50) NOT NULL,
CD_CIDADE INT NOT NULL,
CONSTRAINT PK_BAIRRO PRIMARY KEY (CD_BAIRRO),
CONSTRAINT FK_CIDADE FOREIGN KEY (CD_CIDADE) REFERENCES CIDADE (CD_CIDADE)) 

--INICIADO A PARTIR DO ITEM 33 DO DIA 7/3/2024--
INSERT INTO BAIRRO VALUES ('SAGUAÇU',1)
INSERT INTO BAIRRO VALUES ('VILA DA PENHA',2)
INSERT INTO BAIRRO VALUES ('CENTRO HISTÓRICO',3)
INSERT INTO BAIRRO VALUES ('JARDIM VERA CRUZ',4)
INSERT INTO BAIRRO VALUES ('ALDEOTA',5)
INSERT INTO BAIRRO VALUES ('SANTO ANTÔNIO',3)
INSERT INTO BAIRRO VALUES ('ALTO SÃO BENTO',6)
INSERT INTO BAIRRO VALUES ('VILA DOM PEDRO I',7)
INSERT INTO BAIRRO VALUES ('JARDIM PARAÍSO',8)
INSERT INTO BAIRRO VALUES ('SANTO ANDRÉ',9)
INSERT INTO BAIRRO VALUES ('PORTAIS (POLVILHO)',10)
INSERT INTO BAIRRO VALUES ('VILA CAIÇARA',11)
INSERT INTO BAIRRO VALUES ('VILA ABARCA',12)
INSERT INTO BAIRRO VALUES ('VILA ANDRADE',7)
INSERT INTO BAIRRO VALUES ('VILA FRANCISCO DE TULIO',13)
INSERT INTO BAIRRO VALUES ('NORTE ÁGUAS CLARAS',14)
INSERT INTO BAIRRO VALUES ('CHÁCARA RINCÃO',15)
INSERT INTO BAIRRO VALUES ('ÁGUA FRIA',7)
INSERT INTO BAIRRO VALUES ('NOVA SOROCABA',4)
INSERT INTO BAIRRO VALUES ('PIO-X',16)
INSERT INTO BAIRRO VALUES ('VILA CAMILÓPOLIS',17)
INSERT INTO BAIRRO VALUES ('JARDIM PIRATININGA',18)
INSERT INTO BAIRRO VALUES ('TATUAPÉ',7)
INSERT INTO BAIRRO VALUES ('BARRA DO IMBUÍ',19)
INSERT INTO BAIRRO VALUES ('RECANTO DAS PAINEIRAS',20)
INSERT INTO BAIRRO VALUES ('VILA GURMECINDO',7)
INSERT INTO BAIRRO VALUES ('JARDIM CALIFÓRNIA',21)
INSERT INTO BAIRRO VALUES ('CENTRO',22)
INSERT INTO BAIRRO VALUES ('VILA GUILHERME',7)

SELECT NM_REGIAO 'REGIAO', NM_ESTADO 'ESTADO', DS_SIGLA 'SIGLA', NM_CIDADE 'CIDADE', NM_BAIRRO 'BAIRRO', CD_BAIRRO 'CÓD BAIRRO' FROM REGIAO AS R
INNER JOIN ESTADO AS E ON R.CD_REGIAO=E.CD_REGIAO
INNER JOIN CIDADE AS C ON C.CD_ESTADO=E.CD_ESTADO 
INNER JOIN BAIRRO AS B ON B.CD_CIDADE=C.CD_CIDADE
SELECT NM_CLIENTE 'CLIENTE', CD_CLIENTE 'CÓD CLIENTE' FROM CLIENTE ORDER BY CD_CLIENTE ASC 

CREATE TABLE LOGRADOURO 
(CD_LOGRADOURO INT IDENTITY (1,1) NOT NULL,
NM_LOGRADOURO VARCHAR(80) NOT NULL,
NR_NUMERO INT NULL,
DS_COMPLEMENTO VARCHAR(50) NULL,
DS_REFERENCIA VARCHAR (100) NULL,
NR_CEP VARCHAR(8) NULL,
CD_CLIENTE INT NOT NULL,
CD_BAIRRO INT NOT NULL,
CONSTRAINT PK_LOGRADOURO PRIMARY KEY (CD_LOGRADOURO),
CONSTRAINT FK_CLIENTE FOREIGN KEY (CD_CLIENTE) REFERENCES CLIENTE (CD_CLIENTE),
CONSTRAINT FK_BAIRRO FOREIGN KEY (CD_BAIRRO) REFERENCES BAIRRO (CD_BAIRRO))

--INICIADO A PARTIR DO ITEM 33 DO DIA 7/3/2024--
INSERT INTO LOGRADOURO VALUES ('RUA NATAL',100,'AP 703',NULL,'89221640',1,1)
INSERT INTO LOGRADOURO VALUES ('AVENIDA OLIVEIRA BELO',153,'CASA',NULL,'21221300',2,2)
INSERT INTO LOGRADOURO VALUES ('RUA CORONEL GENUÍNO',194,'AP 1403',NULL,'90010350',3,3)
INSERT INTO LOGRADOURO VALUES ('AV SANTA CRUZ',1485,NULL,'OFICINA VALMIR MARTELINHO','18050260',4,4)
INSERT INTO LOGRADOURO VALUES ('RUA VICENTE LINHARES',211,'AP 604',NULL,'60135270',5,5)
INSERT INTO LOGRADOURO VALUES ('RUA LUIZ DE CAMÕES',903,'AP 403',NULL,'90620150',6,6)
INSERT INTO LOGRADOURO VALUES ('RUA 904',123,NULL,'ENTRA NA RUA DO MATERIAL COSTA','88220000',7,7)
INSERT INTO LOGRADOURO VALUES ('RUA GAMA LOBO',1692,'CASA',NULL,'04269001',8,8)
INSERT INTO LOGRADOURO VALUES ('RUA MAR DEL PLATA',1196,'AP 43','KASATO MARU','12235340',9,9)
INSERT INTO LOGRADOURO VALUES ('RUA F',187,NULL,NULL,'44300000',10,10)

SELECT NM_CLIENTE 'CLIENTE', NM_REGIAO 'REGIAO', NM_ESTADO 'ESTADO', DS_SIGLA 'SIGLA', NM_CIDADE 'CIDADE', NM_BAIRRO 'BAIRRO', NM_LOGRADOURO
'LOGRADOURO', NR_NUMERO 'NÚMERO', DS_COMPLEMENTO 'COMPLEMENTO', DS_REFERENCIA 'REFERÊNCIA', NR_CEP 'CEP'
FROM REGIAO AS R
INNER JOIN ESTADO AS E ON R.CD_REGIAO=E.CD_REGIAO
INNER JOIN CIDADE AS C ON C.CD_ESTADO=E.CD_ESTADO 
INNER JOIN BAIRRO AS B ON B.CD_CIDADE=C.CD_CIDADE
INNER JOIN LOGRADOURO AS L ON L.CD_BAIRRO=B.CD_BAIRRO
INNER JOIN CLIENTE AS CL ON CL.CD_CLIENTE=L.CD_CLIENTE


CREATE TABLE CLIENTE
(CD_CLIENTE INT IDENTITY (1,1) NOT NULL,
NM_CLIENTE VARCHAR(100) NOT NULL,
NR_CPF VARCHAR(11) NULL,
DS_EMAIL VARCHAR(50) NULL,
DT_ANIVERSARIO DATE NULL,
NM_INSTAGRAM VARCHAR(50) NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CD_CLIENTE)) 

--INICIADO A PARTIR DO ITEM 33 DO DIA 7/3/2024--
INSERT INTO CLIENTE VALUES ('ERICA PINOTTI',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('CARMEN DO NASCIMENTO DIAS','09343520700',NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('ELAINE KERN DE ARAÚJO SILVA',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('ALINE LUZINI ANTUNES',NULL,'aluzini.34@gmail.com','03/06/2000',NULL)
INSERT INTO CLIENTE VALUES ('DENYSE OSTERNE GOMES DE FREITAS','14096463353',NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('ROSANA RIBEIRO CARDOSO',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('LUCÉLIA HILLESHEIM','69021775972',NULL,NULL,'@hillesheimlucelia')
INSERT INTO CLIENTE VALUES ('ANA CLAUDIA DE SOUSA ABDO','06677753824',NULL,NULL,'@aninhaabdo10')
INSERT INTO CLIENTE VALUES ('ÉRIKA PIMENTA',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('MIRALVA OLIVEIRA DE SOUZA',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('THAÍS APARECIDA C SILVA','32795665840',NULL,'08/02/1985','@bratzcacheada')
INSERT INTO CLIENTE VALUES ('MARIA ELISABETH DA SILVA VIEIRA','59615109800',NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('CAMILA LIMA',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('TERESA CRISTINA FREIRES HIPÓLITO','16258164803',NULL,NULL,'@tecacristin')
INSERT INTO CLIENTE VALUES ('SOLANGE CRISTINA FERNANDES',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('NEUSA RODRIGUES NASCIMENTO',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('MARLUCE MANTOVANI','21551174855',NULL,NULL,'@marlucem')
INSERT INTO CLIENTE VALUES ('MARIZA MANZI','00376095806','marizamanzi@gmail.com',NULL,NULL)
INSERT INTO CLIENTE VALUES ('MARCIA APARECIDA LUZ DOS SANTOS','06061919840','brunamayara155@gmail.com',NULL,'@santosmarcia1615')
INSERT INTO CLIENTE VALUES ('LEILA MARISA GOULART BOEIRA',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('JANAINA CERQUEIRA','62115910478',NULL,NULL,'@janaina.cerqueira.1973')
INSERT INTO CLIENTE VALUES ('IRACEMA DE PAULA DE FREITAS','32639350110',NULL,NULL,'@iracema_paulanega')
INSERT INTO CLIENTE VALUES ('FÁTIMA CRISTINA C SILVA',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('EUNICE SIGLO',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('ELIANE NOBRE CANTO MARTINS','58803009787',NULL,NULL,'@elianecantomartins')
INSERT INTO CLIENTE VALUES ('CLOTILDE REGINA AZEVEDO GONÇALVES','05913443861',NULL,NULL,'@bordados_pituca')
INSERT INTO CLIENTE VALUES ('CLAUDIA VENTURA MAGATTI MARQUES',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('CLAUDETE CARMONA MARTINES','60573449872','claucarmona@yahoo.com.br',NULL,NULL)
INSERT INTO CLIENTE VALUES ('ANGELA MARIA DE OLIVEIRA AGUIAR',NULL,NULL,NULL,NULL)
INSERT INTO CLIENTE VALUES ('AMABILE APARECIDA MATTA','08271480898',NULL,NULL,'@amabilematta')





  



SELECT NM_CLIENTE 'CLIENTE', 
NM_LOGRADOURO 'LOGRADOURO', NR_NUMERO 'NÚMERO', DS_COMPLEMENTO 'COMPLEMENTO', DS_REFERENCIA 'REF', NR_CEP 'CEP',
NM_BAIRRO 'BAIRRO', NM_CIDADE 'CIDADE', NM_ESTADO 'ESTADO', DS_SIGLA 'SIGLA', CD_ESTADO 'CÓD ESTADO'
FROM LOGRADOURO AS L
INNER JOIN CLIENTE AS CL ON CL.CD_CLIENTE=L.CD_CLIENTE
INNER JOIN BAIRRO AS B ON L.CD_LOGRADOURO=B.CD_LOGRADOURO 
INNER JOIN CIDADE AS C ON C.CD_BAIRRO=B.CD_BAIRRO
INNER JOIN ESTADO AS E ON E.CD_CIDADE=C.CD_CIDADE


DROP TABLE CLIENTE
DROP TABLE LOGRADOURO 
DROP TABLE BAIRRO
DROP TABLE CIDADE 
DROP TABLE ESTADO 

